name: Publish Module

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and deploy artifact
        run: cd main && mvn clean deploy -s .maven/settings.xml
        env:
          EXCHANGE_USERNAME: ${{ secrets.EXCHANGE_USERNAME }}
          EXCHANGE_PASSWORD: ${{ secrets.EXCHANGE_PASSWORD }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
